permalink: :title

highlighter: rouge
markdown: kramdown

title : Chautauqua Land Bank
tagline: Data Dashboard

production_url : labs.orbitist.com/cclb-dashbboard

baseurl : http://labs.orbitist.com/cclb-dashbboard

timezone : America/New_York

category: [map]
