permalink: :title

highlighter: rouge
markdown: kramdown

title : Chautauqua Land Bank
tagline: Data Dashboard

production_url : labs.orbitist.com/cclbc-tiger

baseurl : /cclbc-tiger

timezone : America/New_York

category: [map]
